name: Format

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup shfmt
        uses: mfinelli/setup-shfmt@v3
        
      - name: Format using shfmt
        shell: bash
        run: |
          if (( $(shfmt -l . | wc -l) > 0 ));then
            echo "Code is not properly formatted, please use shfmt."
            echo "Also, you should install and run commit hooks with pre-commit."
            exit 1
          else
            echo "Code is properly formatted"
          fi
          
