name: Lint

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ShellCheck
        shell: bash
        run: find . -type f -name "*.sh" -exec shellcheck {} +
