name: Test

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run e2e tests
        shell: bash
        run: |
          echo "Run a first time to initialize configurations"
          ./build.sh -c "config/examples/Creality/Ender-5 Pro/CrealityV422" -p "STM32F103RC_creality"
          echo "Rune a second time to build the firmware"
          ./build.sh -c "config/examples/Creality/Ender-5 Pro/CrealityV422" -p "STM32F103RC_creality"

